version: '3.8'
services:
  go_service:
    build:
      context: .
      dockerfile: go_service/Dockerfile
    ports:
      - "50051:50051"
    container_name: go_service_container

  rust_service:
    build:
      context: .
      dockerfile: rust_service/Dockerfile
    ports:
      - "50052:50052"
    container_name: rust_service_container

  python_service:
    build:
      context: .
      dockerfile: python_service/Dockerfile
    ports:
      - "50053:50053"
    container_name: python_service_container

  client_service:
    build:
      context: .
      dockerfile: client_service/Dockerfile
    ports:
      - "3001:3001"
    container_name: client_service_container
  client_service_go:
    build:
      context: .
      dockerfile: client_service_go/Dockerfile  # Specify the path to your Go client Dockerfile
    ports:
      - "8585:8585"  # Specify the desired port for your Go client
    container_name: client_service_go_container
    depends_on:
      - go_service  # Ensure that the Go client service starts after the Go server service    

