version: '3.8'
services:
  go_service:
    build:
      context: ./go_service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    container_name: go_service_container

  rust_service:
    build:
      context: ./rust_service
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    container_name: rust_service_container

  python_service:
    build:
      context: ./python_service
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    container_name: python_service_container
